#!/usr/bin/env bash
# Copies the wire types into the extension target.
#
# The extension is a separate Xcode target and cannot link the SPM library
# without a provisioning-profile-bound package reference, so the file is copied
# instead. Run this after any change to Sources/UsageModels.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
src="$root/Sources/UsageModels/UsageSnapshot.swift"
dst="$root/AIUsageSidebar/SampleSidebarExtension/Model/UsageSnapshot.swift"
{
  echo "// Generated by scripts/sync-models.sh. Do not edit."
  echo "// Source of truth: Sources/UsageModels/UsageSnapshot.swift"
  echo
  cat "$src"
} > "$dst"
echo "synced -> $dst"
